// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPc3wdJXWpZn5YZkVoFXgS7ThqPHrwgCI',
    appId: '1:1086355063575:web:6d5da6253d3d0a1a79ed52',
    messagingSenderId: '1086355063575',
    projectId: 'favfood-map',
    authDomain: 'favfood-map.firebaseapp.com',
    storageBucket: 'favfood-map.firebasestorage.app',
    measurementId: 'G-3FJDL48Q9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR-O8gXnRfRdwAGM5ALr3DjfMRgUmWo08',
    appId: '1:1086355063575:android:6536644690e1ba9d79ed52',
    messagingSenderId: '1086355063575',
    projectId: 'favfood-map',
    storageBucket: 'favfood-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8ELpFI4YG7HxKsbavcbvMmQwvkq3AME',
    appId: '1:1086355063575:ios:2e4cb8d5fb6fdc4779ed52',
    messagingSenderId: '1086355063575',
    projectId: 'favfood-map',
    storageBucket: 'favfood-map.firebasestorage.app',
    iosClientId: '1086355063575-1hcn3p01uh60tuu0pu8a0t1gh9ro0sch.apps.googleusercontent.com',
    iosBundleId: 'com.example.favfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm8ELpFI4YG7HxKsbavcbvMmQwvkq3AME',
    appId: '1:1086355063575:ios:2e4cb8d5fb6fdc4779ed52',
    messagingSenderId: '1086355063575',
    projectId: 'favfood-map',
    storageBucket: 'favfood-map.firebasestorage.app',
    iosClientId: '1086355063575-1hcn3p01uh60tuu0pu8a0t1gh9ro0sch.apps.googleusercontent.com',
    iosBundleId: 'com.example.favfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPc3wdJXWpZn5YZkVoFXgS7ThqPHrwgCI',
    appId: '1:1086355063575:web:ec3f879bf9f1358979ed52',
    messagingSenderId: '1086355063575',
    projectId: 'favfood-map',
    authDomain: 'favfood-map.firebaseapp.com',
    storageBucket: 'favfood-map.firebasestorage.app',
    measurementId: 'G-TTDJE8DGYS',
  );
}
